spring.application.name=grievance-core-service

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/grievance_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=samadhan
spring.datasource.password=samadhan123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging:
  level:
    root: INFO
    com.samadhan.grievance_core_service: DEBUG

aws.region=ap-south-1
aws.s3.bucket-name=samadhan-grievance-media
aws.credentials.access-key: AKIA6O45KOXR6NWQDGC2
aws.credentials.secret-key: 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
jwt.secret=SamadhanSecretKeySamadhanSecretKey

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.com.samadhan.grievance_core_service=DEBUG

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


