spring.application.name=samadhan-auth-service
# Server Port
server.port=8081

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/samadhan_auth_db
spring.datasource.username=D2_92575_Shruti
spring.datasource.password=manager

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Settings
jwt.secret=SamadhanSecretKeySamadhanSecretKey
jwt.expiration=86400000
